version: "3.9"

services:
  qwik:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:3000"
    environment:
      NODE_ENV: production
      ORIGIN: ${PUBLIC_SITE_ORIGIN}
    env_file:
      - .env
    restart: unless-stopped
